version: '4.26.1.0'


services:
  app:
    image: internsmanagement
    ports:
      - 9988:9988
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/interns_management_db
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: root
    depends_on:
      - db


  db:
    image: mysql:8
    environment:
      DATABASE_HOST: docker-mysql
      DATABASE_PORT: 3306
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: interns_management_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: root

